-- Versione 4.6: note giornaliere condivise
begin;

create table if not exists public.note_giornaliere (
  id bigint generated by default as identity primary key,
  data_nota date not null unique,
  testo text not null,
  autore_id uuid references auth.users(id),
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nota_non_vuota check (length(trim(testo)) > 0)
);

drop trigger if exists note_giornaliere_updated_at on public.note_giornaliere;
create trigger note_giornaliere_updated_at
before update on public.note_giornaliere
for each row execute function public.imposta_updated_at();

drop trigger if exists registro_note_giornaliere on public.note_giornaliere;
create trigger registro_note_giornaliere
after insert or update or delete on public.note_giornaliere
for each row execute function public.registra_modifica();

alter table public.note_giornaliere enable row level security;

drop policy if exists "Utenti gestiscono note giornaliere" on public.note_giornaliere;
create policy "Utenti gestiscono note giornaliere"
on public.note_giornaliere
for all to authenticated
using (true)
with check (true);

grant select, insert, update, delete on public.note_giornaliere to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
