-- Versione 5.0: impostazioni condivise e registro comunicazioni
begin;

create table if not exists public.impostazioni_app (
  chiave text primary key,
  valore jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.comunicazioni (
  id bigint generated by default as identity primary key,
  tipo text not null,
  destinatario text,
  oggetto text,
  contenuto text,
  record_ids jsonb not null default '[]'::jsonb,
  stato text not null check (stato in ('preparata','inviata')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.impostazioni_app enable row level security;
alter table public.comunicazioni enable row level security;

drop policy if exists "Utenti gestiscono impostazioni" on public.impostazioni_app;
create policy "Utenti gestiscono impostazioni" on public.impostazioni_app for all to authenticated using (true) with check (true);

drop policy if exists "Utenti gestiscono comunicazioni" on public.comunicazioni;
create policy "Utenti gestiscono comunicazioni" on public.comunicazioni for all to authenticated using (true) with check (true);

grant select,insert,update,delete on public.impostazioni_app, public.comunicazioni to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
